# -*- coding: utf-8 -*-
"""딥러닝 입문 02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VxDqu2C201Vm7JJdtzNahKWgVoUDEXA7

# 넘파이 준비하기
"""

import numpy as np 
print(np.__version__) # 버전 확인하기

my_arry = np.array([[10, 20, 30], [40, 50, 60]])
print(my_arry)

type(my_arry)

my_arry[0][2]

np.sum(my_arry)

# 퀴즈
my_arry[1][0]

import matplotlib.pyplot as plt

plt.plot([1, 2, 3, 4, 5], [1, 4, 9, 16, 25]) # x 좌표와 y 좌표를 파이썬 리스트로 전달합니다.
plt.show()

# 2.  산점도 그리기
plt.scatter([1, 2, 3, 4, 5], [1, 4, 9, 16, 25])
plt.show()

# 넘파이 배열로 산점도 그리기
x = np.random.randn(1000)
y = np.random.randn(1000)
plt.scatter(x, y)
plt.show()

plt.scatter(np.random.randn(1000), np.random.randn(1000))
plt.show()

x = np.random.randn(1000)
y = np.random.randn(1000)
plt.rc('font', family = 'NanumBarunGothic')
plt.figure(figsize = (12, 6))
plt.title('Title', fontsize = 15)
plt.xlabel('Samples', fontsize = 15)
plt.ylabel('Counts', fontsize = 15)
plt.scatter(x, y)
plt.show()