# -*- coding: utf-8 -*-
"""11.넘파이 NumPy 배열의 산술연산.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rCTH7NhH5PjYsZcPvSFZ4O3fhWZXJhMG

# 11.넘파이 NumPy 배열의 산술연산
"""

import numpy as np
data = np.array([1, 2])
ones = np.ones(2, dtype = int) # .을 없애주기 위함/ int타입으로 만들어 주었다. 
data, ones

data + ones

data - ones

data * data

data / data

a = np.array([1, 2, 3, 4])
a

a.sum()

b = np.array([[1, 1], [2, 2]])
b

b.sum()

b,