# -*- coding: utf-8 -*-
"""12. 넘파이 NumPy 브로드캐스팅.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QOLzubJuhU7C9Qh4ER_TLxCOnW4Onn1b

# 12. 넘파이 NumPy 브로드캐스팅
"""

import numpy as np
data = np.array([1.0, 2.0]) #스칼라값을 곱해줘도 연산을 할 수 있다. 
data * 1.6

a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])
a + b

a - b

a * b

a / b

a = np.array([[0.0, 0.0, 0.0],
             [10.0, 10.0, 10.0],
             [20.0, 20.0, 20.0],
             [30.0, 30.0, 30.0]])
b = np.array([1.0, 2.0, 3.0])

a.shape, b.shape

a + b

a - b

a * b

a = np.array([[0.0, 0.0, 0.0],
             [10.0, 10.0, 10.0],
             [20.0, 20.0, 20.0],
             [30.0, 30.0, 30.0]])
b = np.array([1.0, 2.0, 3.0, 4.0])

a.shape, b.shape

a + b

a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([1.0, 2.0, 3.0])

a[:, np.newaxis] + b