# -*- coding: utf-8 -*-
"""13. 넘파이 NumPy 1D 2D 집계함수 - np.max, min, std, mean, prod 사용하기.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11AFNMl9DloYjpqWC2PYS0_UnxRG4OGGN

# 13. 넘파이 NumPy 1D 2D 집계함수 - np.max, min, std, mean, prod 사용하기
"""

import numpy as np
data = np.array([1, 2, 3])
data.max()

data.min()

data.sum()

data.mean()  #평균

data.prod() #곱

data.std() # 편차

data.var() #분산

a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

a.shape

a.sum()

a.min()

a.min(axis =0) #축을 기준으로 최솟값들

a.min(axis = 1)

data = np.array([[1, 2], [3, 4], [5, 6]])
data

data.shape

data[0, 1] # 행번호가 0이고 축의 번호가 1인 것

data[1:3] #1행부터 2행까지 가져오기

data[0:2, 0]

"""![](../Data/data.png)"""

data. min()

data.max()

data.sum()

data.mean()

data.std()

data = np.array([[1, 2], [5, 3], [4, 6]])
data

data.max(axis=0)

data.max(axis=1)

data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
data + ones

data - ones

data * ones

data / ones

data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])

data.shape, ones_row.shape

data + ones_row