# -*- coding: utf-8 -*-
"""15. 넘파이 unique 유일값으로 중복된 값은 거르고 보자!.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u-ziza9nEO_P39k3Zx_q6Q6DqHNowZly

# 15. 넘파이 unique 유일값으로 중복된 값은 거르고 보자!
"""

import numpy as np
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
a

np.unique(a)

np.unique(a, return_index = True) #유일값이 처음에 나오는 자리를 알려주었다.

unique_values, indices_list = np.unique(a, return_index=True)
indices_list

unique_values, indices_list, occurrence_count = np.unique(a, 
                                                          return_index=True,
                                                          return_counts=True)
occurrence_count #반복되는 값들이 몇 번 나오는지 알려준다.

a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])
a_2d

np.unique(a_2d) # flattened 형태로 보여준다.

np.unique(a_2d, axis = 0) #기준 :행에서의 유일값

np.unique(a_2d, axis = 1)

unique_rows, indices, occurrence_countnp = np.unique(a_2d, axis=0, return_index=True, return_counts=True)