# -*- coding: utf-8 -*-
"""16. numpy 넘파이 전치행렬과 뒤집기 역.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17_b8MFcTC6s3t3KcgXbMXs3BvTv7eCrS

# 16. numpy 넘파이 전치행렬과 뒤집기 역
"""

import numpy as np
data = np.arange(1, 7)
data

data.size

data.reshape(2, 3)

data.reshape(3, 2)

arr = np.arange(6).reshape((2, 3))
arr

arr.transpose()

arr.T

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
arr

np.flip(arr)

arr[::-1]

arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
arr_2d

np.flip(arr_2d)

np.flip(arr_2d, axis=0) #행을 기준으로 뒤집어 주었다.

np.flip(arr_2d, axis=1) # 열을 기준으로 뒤집어 주었다.

np.flip(arr_2d[1]) # 1번째 행의 값을 역순으로 정렬해 주었다.

np.flip()