# -*- coding: utf-8 -*-
"""17.넘파이 NumPy 1D array flatten ravel 같은 기능을 하지만 무엇이 다를까?.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1otBcWTbK7_zl7-YTJ7J5oIDMV8Dd6T0q

# 18.넘파이 꿀팁 공식문서 보는 단축키는 뭐다?! Numpy help docstring.
"""

import numpy as np
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
x

x.flatten()

x.ravel()

x

a1 = x.flatten()
a1[0] = 99
x

a1

a2 = x.ravel()
a2[0] = 99
x

a2