# -*- coding: utf-8 -*-
"""18.넘파이 꿀팁 공식문서 보는 단축키는 뭐다?! Numpy help docstring..ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/158RNkg8k0BtvXUup_qf-FJWIe4UW4AO5

# 18.넘파이 꿀팁 공식문서 보는 단축키는 뭐다?! Numpy help docstring.
"""

help(max)

max?

max??

max()

import numpy as np
a = np.array([1, 2, 3, 4, 5, 6])
a

a?

def double (a):
    '''
    Return a * 2
    '''
    return a * 2

double?

double?? #소스코드를 볼 수가 있다.