# -*- coding: utf-8 -*-
"""19.넘파이 NumPy 회귀의 오차 측정 공식 MSE RMSE MAE MAPE-Copy1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LJLDihGyklan7G-EceIcEn-VOMFKbrH_

# 19.넘파이 NumPy 회귀의 오차 측정 공식 MSE RMSE MAE MAPE

## MSE(Mean Squared Error)
: 실제값 - 예측값의 차이의 제곱의 평균
"""

import numpy as np
predictions = np.ones(3, dtype = int)
labels = np.arange(1, 4)
mse = (1/3) * np.sum(np.square(predictions - labels))
mse

""" ## RMSE(Root Mean Squared Error)"""

rmse = np.sqrt(mse)
rmse

"""## mae(Mean Absolute Error)
: 예측값과 실제값의 차이에 대한 절댓값의 평균
"""

err = predictions - labels
mae = np.mean(np.abs(err))
mae

"""## MAPE(Mean Absoulte Percentage Error)
: (실제값 - 예측값 / 실제값)의 절댓값에 대한 평균
"""

mape = np.mean(np.abs((predictions - labels) / labels))
mape