# -*- coding: utf-8 -*-
"""20. 넘파이 NumPy 파일저장은 같은 데이터 타입만 되는데 다른 타입 일때는?.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YN_FF8PybWfgonvtwp7zfHhUkNz1ItvH

# 20. 넘파이 NumPy 파일저장은 같은 데이터 타입만 되는데 다른 타입 일때는?
"""

import numpy as np
a = np.array([1, 2, 3, 4, 5, 6])
a

np.save('filename', a)

b = np.load('filename.npy')
b

csv_arr = np.array([1, 2, 3, 4 ,5 ,6 , 7, 8])
csv_arr

np.savetxt('new_file.csv', csv_arr)

np.loadtxt('new_file.csv')

import pandas as pd

a = np.array([1, 2, "3", 4, 5, 6])
a 
# 하나를 문자 형태로 바꾸면 모두가 문자 형태로 바뀐다.

np.save('filemane', a)

np.load('filemane.npy')

csv_arr = np.array([1, 2, 3, 4 ,"5" ,6 , 7, 8], dtype=int)
csv_arr

np.savetxt('new_file.csv', csv_arr)

"""numpy에서는 모두가 숫자열이나 문자열이어야만 그 형태로 저장이 된다. savetxt에서는 문자열이 저장되지 않는다."""

music = [['Billie Holiday','Jazz', 1300000, 27000000],
 ['Jimmie Hendrix', 'Rock', 2700000, 70000000],
 ['Miles Davis', 'Jazz', 1500000, 48000000],
 ['SIA', 'Pop', 2000000, 74000000]]

df = pd.DataFrame(music)
df

df.to_csv("music.csv", index = False)

pd.read_csv('music.csv')

"""pandas를 사용하여 데이터를 저장하는 것을 추천한다."""

a = np.array([[-2.58289208,  0.43014843, -1.24082018, 1.59572603],
              [ 0.99027828, 1.17150989,  0.94125714, -0.14692469],
              [ 0.76989341,  0.81299683, -0.95068423, 0.11769564],
              [ 0.20484034,  0.34784527,  1.96979195, 0.51992837]])
a

df = pd.DataFrame(a)

df.to_csv('pd.csv')

pd.read_csv("pd.csv")

np.savetxt('np.csv', a, fmt='%.2f', 
           delimiter=',', header='1,  2,  3,  4')
# delimiter를 이용하여 구분해 달라
# fmt='%.2f' 소수점 둘째자리수까지 보여달라

"""![](../Data/2021.04.05.png)"""

cat np.csv