# -*- coding: utf-8 -*-
"""21.넘파이 NumPy 이미지는 왜 3차원일까, 내가 찍사진을 넘파이 배열로 만들어 볼까?.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UZIcEuMTbrL_qG_nwJ4XjRjIWlWAMxf4

## 21.넘파이 NumPy 이미지는 왜 3차원일까, 내가 찍사진을 넘파이 배열로 만들어 볼까?
"""

from scipy import misc

img = misc.face()
img

img.ndim #ndim 몇차원인지 알아보기

img.size

img.shape

type(img)

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
# %matplotlib inline

plt.imshow(img)

img[:, :, 0].shape # 행이 768개, 컬럼이 1024이다.

img[:, :, 1]

img[:, :, 2]

"""RGB(가산혼합), CMYK"""

plt.imshow(img[:, :, 0])

plt.imshow(img[:, :, 1])

plt.imshow(img[:, :, 2])

img[0, 0]

img_array = img / 255
img_array

plt.imshow(img_array)

img_array.shape

img_gray = img_array @ [0.2126, 0.7152, 0.0722]
img_gray

img_gray.shape

plt.imshow(img_gray, cmap='Greys')