# -*- coding: utf-8 -*-
"""22. 넘파이 NumPy 행렬곱으로 이미지를 그레이스케일로 바꾸는 공식이 있다..ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13icTMqRSyvDqeM4q1ayg4lbYvpOizmbV

# 22. 넘파이 NumPy 행렬곱으로 이미지를 그레이스케일로 바꾸는 공식이 있다.
"""

3 * 4 *3

import numpy as np
a = np.arange(1, 37).reshape(3, 4, 3)
a

a @ [2, 2, 2]

b = (a[:, :, 0] * 2) + (a[:, :, 1] * 2) + (a[:, :, 2] * 2)
b

b.shape

a @ [0.2126, 0.7152, 0.0722]

(a[:, :, 0] * 0.2126) + (a[:, :, 1] * 0.7152) + (a[:, :, 2] * 0.0722)