# -*- coding: utf-8 -*-
"""2. 파이썬은 느린데 넘파이는 빠르다?.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pcMJPGiUZkG6klkKRXVA1g6hH1XEQIVe

# title
"""

import numpy as np

a = np.arange(5)
a

b = np.arange(5, 10)
b

c = []
for i in range(len(a)):
    c.append(a*b)
c

# Commented out IPython magic to ensure Python compatibility.
# %%timeit
# d = []
# for r in range(len(a)):
#     d.append(a[r]*b[r])
# d # 마이크로 세컨드

# Commented out IPython magic to ensure Python compatibility.
# %%timeit
# c = a * b
# c # 나노 세컨드