# -*- coding: utf-8 -*-
"""5.배열을 만드는 여러 방법.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b77_Adshsz3jVi7EhStChxxgZxm9QDV2

# 배열을 만드는 방법 여러 방법
- np.array(), np.zeros(), np.ones(), np.empty(), np.arange(), np.linspace(),dtye
"""

import numpy as np # 넘파이의 배열 형태로 array를 저장하게 된다. 백터 형태로 값이 만들어 진다. 
a = np.array([1, 2, 3])

np.zeros(2)

np.zeros([2, 3])

np.ones(2)

np.ones([2, 3])

np.empty(2) # 안의 값들은 임으로 생성이 된다.

np.empty([2, 3])

"""## 배열 생성 속도 비교

![](../Downloads/array.png)
"""

np.zeros(5)# 여러번 실행하고 평균 시간을 반환한다.

# Commented out IPython magic to ensure Python compatibility.
# %timeit np.zeros(5)

np.ones(5)

# Commented out IPython magic to ensure Python compatibility.
# %timeit np.ones

np.empty(5)

# Commented out IPython magic to ensure Python compatibility.
# %timeit np.empty

np.linspace(1, 10, 5)

np.arange(5)

# Commented out IPython magic to ensure Python compatibility.
# %timeit np.arange



