# -*- coding: utf-8 -*-
"""7.ndim, size, shape.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FgfvrPc_K61xHpyPvsnT2M5Zc2dfCfMf

# 07.ndim, size, shape
"""

import numpy as np
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])
array_example

array_example.ndim

array_example.size

array_example.shape

"""## arr.reshape()"""

a = np.arange(6)
a





# a를 reshape 해 주었나, np.reshape를 만들고 a 라는 데이터를 넣어주었나?