# -*- coding: utf-8 -*-
"""8.넘파이 배열 축 추가하기 np.newaxis, np.expand_dims().ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YL1UsGuC7oJuZ7fEc47m2hhMClRvN8Ba

# 넘파이 배열 축 추가하기 np.newaxis, np.expand_dims()
"""

import numpy as np
a = np.array([1, 2, 3, 4, 5, 6])
a

a.shape

a2 =  a[np.newaxis, :] # 2차원의 형태로 만들어 준다. 
a2.shape

row_vertor = a[np.newaxis, :]
row_vertor

row_vertor.shape

col_vector = a [: , np.newaxis] # 행을 그래도 열을 바꿔준다. 
col_vector

col_vector.shape

b = np.expand_dims(a, axis=1) # 컬럼 벡터
b

