# -*- coding: utf-8 -*-
"""cold_treatment_weather_environment (1).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19OtffQ4JKdyTIT5OksxEVI_OXy7XJwBz
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

def main(df : pd.DataFrame):
    global COLUMN_NAME_LIST_ENG, COLUMN_NAME_LIST_KOR, COLUMN_NAME_DICT
    if not COLUMN_NAME_LIST_KOR:
        COLUMN_NAME_LIST_KOR = list(df.columns)
    if not COLUMN_NAME_DICT:
        COLUMN_NAME_DICT = dict(zip(COLUMN_NAME_LIST_KOR, COLUMN_NAME_LIST_ENG))
    df = changeColumnName(df, COLUMN_NAME_DICT)
    return

def changeColumnName(df : pd.DataFrame, columnDict : dict):
    df.rename(columns = columnDict, inplace=True)
    return df

rawData = pd.read_excel('../Data/cold_treatment_weather_environment.xlsx', None)

del rawData['SNS']

COLUMN_NAME_LIST_ENG = ['date', 'medicalTreatmentCount', 'meanTemp', 'maxTemp',
                        'minTemp', 'humidity', 'minHumidity', 'precipitation',
                        'windSpeed', 'maxWindSpeed', 'sunshine', 'solarRadiation',
                        'airPressure', 'sulfurousAcidGas', 'FindDust',
                        'nitrogenDioxide', 'ozone', 'carbonMonoxide']

COLUMN_NAME_LIST_KOR = None

COLUMN_NAME_DICT = None

for sheet in rawData:
    main(rawData[sheet])

