# -*- coding: utf-8 -*-
"""넘파이 배열을 만드는 여러 방법 .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ttj2K-i1lhigW5qslbZkmv0b84G5RC2p
"""

import numpy as np

a = np.array([1, 2, 3])
a

np.zeros(2)

np.zeros(3)

np.zeros([2, 3])

np.ones(2)

np.ones([2, 3])

np.empty(2) # 임의로 생성되는 숫자들 (빠르게 만들고 싶을 때)

np.empty([2, 3])

np.arange(1, 11, 3)

np.linspace(0, 10, num=5) # 선형 수학 균일한 간격으로 num 갯수 만큼 나오게 한다.

np.linspace(0, 10, num=10)

