# -*- coding: utf-8 -*-
"""절재적인 기본 -list 와 np.array의 차이.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1loTlQGCSQayj1WBeHHANLgjI91ULdwOc
"""

import numpy as np

a = np.arange(6)
a

np.newaxis # 새로운 축을 만들어 주었다. 
a2 = a[np.newaxis, :]
a2

np.newaxis # 새로운 축을 만들어 주었다. 
a2 = a[np.newaxis, 1]
a2

a.shape, a2.shape # 1차원에서 2차원으로 간다

a_list = [0, "1", 2.0, 3] # 아직 잘 모릅니다. 제가 생각보다 능력이 뛰어나진 않습니다.
type(a_list)

np.array(a_list) # 다 같은 형태(문자)로 들어가 있다.# 이것도 잘 이해를 못 했습니다.

"""배열이란 무엇일까?"""

a = np.array([1, 2, 3, 4, 5, 6])
a

a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

